AWSTemplateFormatVersion: '2010-09-09'
Transform:
  - AWS::SecretsManager-2020-07-23
  - AWS::Serverless-2016-10-31
Description: >-
  Aurora Postgres Database IAM, KMS and Secrets

Parameters:
  OU:
    Type: String
    Default: demo
  PlatForm:
    Type: String
    Default: dev
  Project:
    Type: String
    Default: rds-infra

Resources:

  ##Database Failover Lambda Execution Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: Explicit name is required to allow this to be used in other template
          - id: W11
            reason: Some * are unavoidable, all resources are limited by account as a minimum
    Properties:
      RoleName: !Sub ${OU}-iam-${PlatForm}-${Project}-${AWS::Region}-lambda-exec-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - events.amazonaws.com
                - apigateway.amazonaws.com
                - rds.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: !Sub ${OU}-iam-${PlatForm}-${Project}-lambda-execution-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:DescribeLogStreams
                  - logs:DescribeLogGroup
                  - logs:PutLogEvents
                  - logs:PutRetentionPolicy
                  - logs:GetLogEvents
                  - logs:FilterLogEvents
                Resource:
                  - !Sub arn:aws:logs:*:${AWS::AccountId}:log-group:*
                  - !Sub arn:aws:logs:*:${AWS::AccountId}:log-group:*:log-stream:*
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:PutParameter
                Resource:
                  - !Sub arn:aws:ssm:*:${AWS::AccountId}:parameter/demo/*
              - Effect: Allow
                Action:
                  - xray:PutTraceSegments
                  - xray:PutTelemetryRecords
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:Encrypt
                  - kms:ReEncrypt*
                  - kms:GenerateDataKey*
                  - kms:DescribeKey
                Resource:
                  - !Sub arn:aws:kms:*:${AWS::AccountId}:alias/${OU}-kms-*
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - '*'
              # - Effect: Allow
              #   Action:
              #     - iam:PassRole
              #   Resource:
              #     - !GetAtt DBProxyRole.Arn
              - Effect: Allow
                Action:
                  - route53:GetHostedZone
                  - route53:ChangeResourceRecordSets
                  - route53:GetChange
                  - route53:GetTrafficPolicyInstance
                  - route53:ListResourceRecordSets
                Resource:
                  - arn:aws:route53:::hostedzone/*
              - Effect: Allow
                Action:
                  - SNS:Publish
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - rds:FailoverGlobalCluster
                  - rds:RemoveFromGlobalCluster
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - ecs:ListTasks
                  - ecs:stopTask
                  - ecs:StartTask
                Resource: 
                  - '*'
  LambdaExecutionRoleARN:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /demo/rds/iam/lamdaexecutionrole
      Type: String
      Value:  !GetAtt LambdaExecutionRole.Arn
      Description: Lambda Execution Role for RDS Failover
